# Handle submodule and lfs dependencies
.git_sub: &git_sub |
  git submodule update

# alter the behaviour of installer scripts
variables:
  CI_BUILD: "1"

stages:
  - build
  - test


# Use ubuntu image to isolate build env
# allow use of root and installing depends as
# occurs in dpeloy env
build:tool:
  image: ubuntu
  before_script:
    - *git_sub
    - ./tooling/installer.sh
  script:
    - cd tooling/prod
    - make

test:tool:
  image: ubuntu
  before_script:
    - ./tooling/installer.sh
  script:
    - cd tooling/prod
    - make clean
    - make test

build:ethics:
  before_script:
    - *git_sub
    - apt install unoconv
  script:
    - cd administriva/ethics
    - unoconv -f pdf *.odt
  artifacts:
    paths:
      - "administriva/ethics/*.pdf"

build:dissertation:
  image: blang/latex
  tags:
    - docker
  script:
    - cd dissertation && latexmk -pdf l4proj.tex
  artifacts:
    paths:
      - "dissertation/*.pdf"

