# alter the behaviour of installer scripts
variables:
  CI_BUILD: "1"
  DEBIAN_FRONTEND: "noninteractive"

stages:
  - build
  - test

build:tool:
  image: ubuntu
  script:
    - ./tooling/installer.sh

test:tool:
  image: ubuntu
  before_script:
    - apt-get update --yes && apt install --yes libcunit1-dev
  script:
    - ./tooling/installer.sh
    - cd tooling/prod
    - make clean
    - make test

build:ethics:
  before_script:
    - apt-get update --yes && apt install --yes unoconv
  script:
    - cd administriva/ethics
    - unoconv -f pdf *.odt
  artifacts:
    paths:
      - "administriva/ethics/*.pdf"

build:dissertation:
  image: blang/latex
  tags:
    - docker
  script:
    - cd dissertation && latexmk -pdf l4proj.tex
  artifacts:
    paths:
      - "dissertation/*.pdf"
